default-resources:
    slurm_account: "m2_zdvhpc"
    slurm_partition: "smp"
    cpus_per_task: 1
    mem_mb_per_cpu: 1800
    runtime: "1h"

set-resources:
    genome_to_transcriptome:
        runtime: "2h"

    build_minimap_index:
        cpus_per_task: 4
        mem_mb_per_cpu: 3600

    map_reads:
        cpus_per_task: 40
        runtime: "3h"
        slurm_partition: "parallel"

    plot_samples:
        cpus_per_task: 4
        runtime: "3h"
    
    plot_all_samples:
        cpus_per_task: 8
        runtime: "2h"

    map_qc:
        cpus_per_task: 8

    sam_sort:
        cpus_per_task: 4
        runtime: "2h"

    sam_index:
        cpus_per_task: 8
        runtime: "30m"

    sam_stats:
        cpus_per_task: 8
        runtime: "30m"

    count_reads:
        cpus_per_task: 8

    de_analysis:
        cpus_per_task: 4
        mem_mb_per_cpu: 5000

