default-resources:
    slurm_account: "m2_zdvhpc"
    slurm_partition: "smp"

set-resources:
    build_minimap_index:
        cpus_per_task: 4
        mem_mb_per_cpu: 3600
        runtime: "1h"

    map_reads:
        cpus_per_task: 40
        mem_mb_per_cpu: 1800
        runtime: "3h"
        slurm_partition: "parallel"

    plot_samples:
        cpus_per_task: 1
        mem_mb_per_cpu: 1800
        runtime: "5h"
    
    plot_all_samples:
        cpus_per_task: 8
        mem_mb_per_cpu: 1800
        runtime: "2h"

    sam_sort:
        cpus_per_task: 8
        mem_mb_per_cpu: 1800
        runtime: "1h"

    sam_index:
        cpus_per_task: 8
        mem_mb_per_cpu: 1800
        runtime: "30m"

    sam_stats:
        cpus_per_task: 8
        mem_mb_per_cpu: 1800
        runtime: "30m"

    count_reads:
        cpus_per_task: 8
        mem_mb_per_cpu: 1800
        runtime: "1h"

    de_analysis:
        cpus_per_task: 4
        mem_mb_per_cpu: 5000
        runtime: "1h"
