default-resources:
    slurm_account: "nhr-zdvhpc"
    slurm_partition: "smallcpu"

set-resources:
    genome_to_transcriptome:
        cpus_per_task: 1
        mem_mb_per_cpu: 1800
        runtime: "30m"
    
    filter_reads:
        cpus_per_task: 1
        mem_mb_per_cpu: 1800
        runtime: "2h"

    build_minimap_index:
        cpus_per_task: 4
        mem_mb_per_cpu: 3600
        runtime: "30m"

    map_reads:
        threads: 32
        mem_mb_per_cpu: 1800
        runtime: "3h"
        slurm_partition: "smallcpu" # needs benchmarking

    plot_samples:
        cpus_per_task: 4
        mem_mb_per_cpu: 1800
        runtime: "3h"
    
    plot_all_samples:
        cpus_per_task: 8
        mem_mb_per_cpu: 1800
        runtime: "2h"

    map_qc:
        cpus_per_task: 8
        mem_mb_per_cpu: 1800
        runtime: "1h"

    bam_sort:
        cpus_per_task: 4
        mem_mb_per_cpu: 7200
        runtime: "2h"

    sam_to_bam:
        cpus_per_task: 1
        mem_mb_per_cpu: 1800
        runtime: "1h"

    bam_index:
        cpus_per_task: 8
        mem_mb_per_cpu: 1800
        runtime: "30m"

    bam_stats:
        cpus_per_task: 8
        mem_mb_per_cpu: 1800
        runtime: "30m"

    count_reads:
        cpus_per_task: 8
        mem_mb_per_cpu: 1800
        runtime: "1h"

    de_analysis:
        cpus_per_task: 8
        mem_mb_per_cpu: 5000
        runtime: "1h"
