name: Announce Release on Mastodon

on:
  push:
    branches:
      - main
    path:
      - 'CHANGELOG.md'

permissions:
  pull-requests: read

jobs:
  post_to_mastodon:
    if: "${{ contains(github.event.head_commit.message, 'chore(main): release') }}"
    runs-on: ubuntu-latest
    steps:
      - name: Post to Mastodon
        uses: snakemake/mastodon-release-post-action@main # == latest
        with:
          access-token: ${{ secrets.MASTODONBOT }}
          pr-title: ${{ github.event.head_commit.message }}
          image: "rulegraph.png"
          image-description: "rulegraph of the workflow"
          message: |
            Beep, Beep - I am your friendly #Snakemake release announcement bot.
            
            There is a new release of the Snakemake executor of the rna-longseq-de-isoform workflow. Its version now is {{ version }}!
            
            You can find the workflow in the Snakemake workflow catalog: https://snakemake.github.io/snakemake-workflow-catalog/.
            
            If you want to discuss the release, you will find one maintainers here on Mastodon!
            @rupdecat .
            
            If you discover any issues, please report them on {{ issue_url }}.

            See {{ changelog }} for details. Here is the header of the changelog:
            
            ${{ steps.extract-release-notes.outputs.release_notes }}
            
